# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np
X = np.random.random((6,6,6))
print(X)

[[[0.85359065 0.40188082 0.18719469 0.53382898 0.92517408 0.57501783]
  [0.65182442 0.86775173 0.43237386 0.97784864 0.01472034 0.47925369]
  [0.8023943  0.0165899  0.14771322 0.77272792 0.65010061 0.45800181]
  [0.93624214 0.02297174 0.4793994  0.66992132 0.91605392 0.73958542]
  [0.59517281 0.24117909 0.00154907 0.85205674 0.2282033  0.9984578 ]
  [0.50507169 0.89693858 0.98656735 0.71614564 0.84503785 0.38274428]]

 [[0.44014327 0.81566528 0.47345936 0.05586608 0.57253505 0.81722408]
  [0.67954681 0.35712892 0.01868582 0.79152029 0.1218604  0.71484531]
  [0.64698913 0.6464314  0.75063787 0.41184785 0.53570872 0.46928506]
  [0.59089428 0.86834128 0.39224618 0.94061773 0.49702623 0.1909247 ]
  [0.60583652 0.76866028 0.43421007 0.79824027 0.43223806 0.7487909 ]
  [0.18631826 0.17585401 0.56047991 0.41841046 0.16580708 0.96449021]]

 [[0.65910085 0.14392015 0.56070332 0.17530706 0.62108848 0.07628317]
  [0.00180178 0.42645923 0.87745253 0.95252978 0.67612404 0.48295484]
  [0.25655933 0.

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [6]:
import numpy as np
X = np.diag(1+np.arange(4),k=-1)

print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
import numpy as np
x = np.ones((4,4))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.28723142 0.8319183  0.65453032 0.86116741 0.6291539 ]
 [0.35772255 0.02571337 0.20044694 0.20683751 0.42444209]
 [0.94624268 0.59211214 0.65326586 0.907513   0.61254332]
 [0.45297296 0.53861502 0.96254221 0.54692262 0.70244672]
 [0.01478427 0.61679959 0.19590323 0.16396052 0.2645702 ]]
After normalization:
[[0.28746491 0.86217587 0.67500996 0.89303724 0.64823474]
 [0.36184163 0.01153153 0.19589672 0.20263954 0.43223886]
 [0.98280201 0.60915118 0.6736758  0.94193748 0.63070857]
 [0.46234241 0.55270521 1.         0.56147073 0.7255676 ]
 [0.         0.63519944 0.19110255 0.1573991  0.26355456]]


# 5.  How to find common values between two arrays?

In [11]:
import numpy as np
array1 = np.array([0, 10, 20, 44, 60])
print("Array1: ",array1)
array2 = [20, 44, 55]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 44 60]
Array2:  [20, 44, 55]
Common values between two arrays:
[20 44]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
import numpy as np
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-27
2020-08-28
2020-08-29


# 7. Consider two random array A and B, check if they are equal

In [14]:
import numpy as np
A = np.random.randint(0,5,10)
B = np.random.randint(0,5,10)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [17]:
import numpy as np
x = np.random.random(20)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Maximum value replaced by 0:
[0.09446904 0.309744   0.71547035 0.44000755 0.83375126 0.17471039
 0.20784199 0.44223033 0.58373289 0.44555593 0.41681038 0.11807318
 0.73458224 0.42282848 0.         0.13063057 0.84604805 0.47823573
 0.38159935 0.00367729]


# 9. How to print all the values of an array?

In [32]:
import numpy as np
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((20,20))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

# 10.Subtract the mean of each row of a matrix

In [34]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(15, 25)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

Original matrix:


Subtract the mean of each row of the said matrix:

[[0.18188011 0.53465234 0.70147451 0.96631258 0.17110234 0.43878427
  0.977935   0.13959814 0.19071431 0.69785977 0.60282951 0.47049939
  0.12522217 0.59435253 0.720435   0.25665079 0.3553403  0.0372632
  0.75093603 0.95583417 0.7154048  0.0435624  0.66618065 0.14420369
  0.44450979]
 [0.30387809 0.10292894 0.87813086 0.34346022 0.92512077 0.49797031
  0.43973533 0.63698164 0.96700524 0.65988235 0.09157454 0.65437617
  0.52245175 0.32699649 0.32217356 0.9398986  0.92126645 0.57839568
  0.89808663 0.17793159 0.55945182 0.69888374 0.25322216 0.09095123
  0.29578335]
 [0.48345781 0.81158351 0.66823073 0.50106088 0.60845063 0.04657356
  0.23209857 0.82784887 0.06958883 0.69863406 0.16090859 0.96304188
  0.613641   0.55880314 0.16560575 0.50428871 0.89918523 0.32881927
  0.52675033 0.74685063 0.3207551  0.21698945 0.1208879  0.99178313
  0.36520205]
 [0.59922814 0.17713497 0.7939507  0.96696247 0.00173159 0.87133559
  0.2

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [35]:
import numpy as np
Z = np.ones(30)
I = np.random.randint(0,len(Z),40)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 2. 3. 2. 3. 3. 1. 2. 4. 4. 1. 2. 3. 3. 2. 2. 2. 2. 3. 2. 1. 3. 4.
 1. 1. 3. 3. 3. 2.]


In [36]:
import numpy as np
np.add.at(Z, I, 1)
print(Z)

[3. 1. 3. 5. 3. 5. 5. 1. 3. 7. 7. 1. 3. 5. 5. 3. 3. 3. 3. 5. 3. 1. 5. 7.
 1. 1. 5. 5. 5. 3.]


# 12.How to get the diagonal of a dot product?

In [37]:
import numpy as np
A = np.random.uniform(0,1,(15,15))
B = np.random.uniform(0,1,(15,15))
print(A)
print(B)

prod1=np.diag(np.dot(A, B))


prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.96582649 0.28841391 0.86206741 0.1288358  0.24838873 0.69817747
  0.26885971 0.80956408 0.42661517 0.98796749 0.37348173 0.80145774
  0.68153992 0.17212204 0.01167719]
 [0.05208541 0.49025149 0.5340604  0.55108434 0.56709854 0.30783264
  0.61447378 0.5756751  0.59135766 0.63924027 0.50977098 0.31481174
  0.65065052 0.23866421 0.75205073]
 [0.76042785 0.92769419 0.8457347  0.7193841  0.85364415 0.64543328
  0.63716696 0.70649462 0.16561377 0.36252937 0.76087588 0.5982652
  0.67992397 0.61729805 0.40174445]
 [0.99712708 0.11198836 0.47515292 0.55066058 0.39463527 0.00174151
  0.7187589  0.43216625 0.55439908 0.77335861 0.0107818  0.64815828
  0.5355319  0.86655892 0.69747941]
 [0.89684207 0.94993366 0.58217124 0.20414221 0.11301281 0.00346436
  0.10404798 0.17961849 0.98833811 0.81402862 0.79891345 0.12630491
  0.53643082 0.2357996  0.89707901]
 [0.28676557 0.26466283 0.94252542 0.85468698 0.62109692 0.97694781
  0.81467403 0.66978107 0.07667    0.53450735 0.75715734 0.50098647
  0.1

# 13.How to find the most frequent value in an array?

In [38]:
import numpy as np
x = np.random.randint(0, 23, 47)
print(x)
print(np.bincount(x).argmax())

[10 13 19  1 14 19 20 20  4 14 20 22  3  5 17 22  9  7 12  0 18 11 14  6
 18 17 22 22 20 11 12  8 18  1  8  4 13 16 22  0 17 18  8  2 18  8 12]
18


# 14.How to get the n largest values of an array

In [41]:
import numpy as np
x = np.arange(1000)
np.random.shuffle(Z)
n = 10

print (Z[np.argsort(Z)[-n:]])

[5. 5. 5. 5. 5. 5. 5. 7. 7. 7.]


# 15.How to create a record array from a regular array?

In [46]:
import numpy as np
X = np.array([("Namasthe", 4.7, 2),
              ("India", 3.5, 2)])
Y = np.core.records.fromarrays(X.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Y)

[(b'Namasthe', 4.7, 2) (b'India', 3.5, 2)]
